project:
  type: website

execute: 
  tidy: true

exclude:
  - "*.R"
  - "Files/"
  
website:
  title: "My Manual for Fiscal Futures"
  site-url: https://jahunlee.github.io/Fiscal-Futures
  navbar:
    left:
      - href: index.qmd
        text: Home